modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="tloa"
version="0.1.1"
displayName="The Legend of Alex"
displayURL="https://mcreator.net"
credits="Tucky143"
authors="Tucky143"
description="The Legend of Alex, a Zelda based mod."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tloa]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tloa]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration