modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="tlos"
version="0.0.1"
displayName="The Legend of Steve"
displayURL="https://mcreator.net"
credits="Tucky143"
authors="Tucky143"
description="The Legend of Zelda: Minecraft Edition"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tlos]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tlos]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration